### PR TITLE
fixed csvdir import error

### PR DESCRIPTION
**Pull request by ramashisx**
the previous line to check the code with iterator was emptying the iterator.

### CODE REVIEW

**Review by MBounouar — APPROVED** [review]
Thanks for the fix.
Although not an absolute necessity,  I would maybe keep the is_file() check.

`fnames = {f.name.split(".")[0]: f.name for f in files if f.is_file()}`

**Comment by ramashisx** [comment]
> 

done

**Comment by ramashisx** [comment]
> 

sorry accidentally closed it

**Comment by ramashisx** [comment]
> 

sorry accidentally closed it

**Comment by stefan-jansen** [comment]
Maybe use `f.stem` instead of `f.name.split...`?

**Review by stefan-jansen — APPROVED** [review]

**Pull request merged**
