### PR TITLE
Fix connection pool

### PR DESCRIPTION
**Pull request by stefan-jansen**
Addresses #209.

### CODE REVIEW

**Comment by stefan-jansen** [comment]
@MBounour - adding the fix proposed by @RichardDale; just let me know if you have a better alternative in mind. Looks like something our tests missed.

**Comment by RiseT** [comment]
@MBounouar (sorry, just fixing alias typo 😉 )

**Comment by MBounouar** [comment]
> @MBounouar - adding the fix proposed by @RichardDale; just let me know if you have a better alternative in mind. Looks like something our tests missed.
Unfortunately, I don't have a better alternative. I vaguely remember about this issue when playing with SQLAlchemy 2.0 several months ago, but I completely forgot about it and never encountered any issue with Linux or WSL.

The whole sql reading and writing in zipline is a bit awkward, even more so with SQLAlchemy 2.0.  Refactoring the code or at least investigating potential improvements would make sense. I have the impression that the whole ingestion process is suspiciously slow. However, I don't think I will be able to pick that up any time soon

**Comment by RichardDale** [comment]
Thanks Stefan and Mehdi - looking forward to this being pushed to conda-forge so our users can upgrade.

**Pull request merged**
