### PR TITLE
Replace talib with pandas

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@stefan-jansen please approve workflow run

**Comment by MBounouar** [comment]
Hi, I am not sure removing talib is a good idea.
First keeping the filename the same is confusing, second there are two files that do very similar things already, namely `dual_moving_average.py`,  `dual_ema_talib.py`. I think the original idea of the example, was to show how to use  `talib`. 
Why not add an example using pandas there ?

**Comment by gliptak** [comment]
Thank you @MBounouar talib was last updated/released a decade ago https://sourceforge.net/projects/ta-lib/ and is not package manager and Pypi (wheel) installable (at least under Linux). I would like to see it removed as a (hard) install dependency. This PR is first step accomplishing.
Are there other (install friendlier) financial indicator packages which could be used to demonstrate usage instead?

**Comment by MBounouar** [comment]
Despite not being maintained anymore, talib is still fairly popular and I don't know of any "better" (regularly maintained) replacement. 
The python bindings [https://github.com/ta-lib/ta-lib-python](https://github.com/ta-lib/ta-lib-python)  are regularly maintained.

Starting a Rust port has been in the back of my head for sometime now though :stuck_out_tongue_winking_eye: 

Making ta-lib an extra dependency of zipline would make more sense in my opinion.

Linux install of ta-lib is (at least for me) way more straightforward and easier compared to windows.

**Comment by gliptak** [comment]
some talib alternatives:

* https://github.com/twopirllc/pandas-ta
* https://github.com/bukosabino/ta
* https://github.com/nardew/talipp
* https://github.com/pmorissette/ffn

**Comment by MBounouar** [comment]
Thanks for sharing.
Indeed, some of them are interesting replacements.
I still think that the first step would be to decouple `ta-lib` from zipline, i.e. make it an optional dependency and adjust the test scripts and examples (`test_technical.py`, `test_algorithms.py`. ...) so that they don't crash because of the missing dependency.

**Pull request closed without merging**
